# Generated by Django 4.2 on 2023-04-24 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_alter_album_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='name',
            new_name='artist',
        ),
    ]
